### ISSUE TITLE
Split ratio changing while using it

### ISSUE THREAD

**Issue by cvignal** [NvChad/nvterm#22] opened 2022-09-08 09:02 UTC
Hello, I've been trying to use nvterm but I'm not a fan of the default split ration for vertical terminal and tried to change it to 0.3. It does work when opening the terminal but the ratio changes back to 0.5 (the default) when certain events occur such as opening NvimTree.
Here is a recording to show what I mean.
[video-nvterm.webm](https://user-images.githubusercontent.com/1612975/189089247-58269bb8-da51-4cb5-8194-47f2f22bb909.webm)

Thanks in advance for your help

**Comment by theowenyoung** [comment] 2022-09-25 17:45
Yes, I can reproduce this error. just setting up a fresh NvChad, here is the path to reproduce:

```
nvim
:edit test.txt
<C-n>
<C-l>
<M-h>
<C-x><C-w>k
```

then the horizontal terminal window will expand to 0.5 ratios, it's really annoying.

**Comment by theowenyoung** [comment] 2022-09-25 17:58
It seems this setting cause this error: 


https://github.com/NvChad/NvChad/blob/27560319cc4cf753e5a4d8713f82206d84a70d61/lua/plugins/configs/nvimtree.lua#L26


when it was `false`, everything is fine.

**Comment by zbirenbaum** [comment] 2022-09-27 04:43
If this is an nvim-tree issue, is it safe to close this? I'm a bit lost on whether there's anything actionable inside of nvterm based on the linked issues.

**Comment by siduck** [comment] 2022-09-27 05:18
> If this is an nvim-tree issue, is it safe to close this? I'm a bit lost on whether there's anything actionable inside of nvterm based on the linked issues.

it seems like the split-ratio gets changed when toggling nvimtree, so @cvignal most probably wants to have a fixed split-ratio

**Comment by siduck** [comment] 2022-09-27 05:19
@cvignal but this behaviour happens with normal buffers too, try this 

Open a file in vertical split and resize it , then toggle nvimtree. The same thing happens!

So this is most probably a nvimtree issue

**Comment by theowenyoung** [comment] 2022-09-27 13:08
yes, it is most probably a nvimtree issue, even `adaptive_size=false`, the split-ratio gets changed when toggling nvimtree.

**Comment by husnaram** [comment] 2022-10-24 12:52
same here. when nvimtree close, and trying to move to editor and terminal, the issue does not occur.

**Comment by siduck** [comment] 2022-10-24 12:55
> same here. when nvimtree close, and trying to move to editor and terminal, the issue does not occur.

its a nvimtree issue

**Comment by VioletXF** [comment] 2023-01-03 12:37
It's not a bug, it's a feature.
Simply add this option to nvim-tree

```
view = {
...
  preserve_window_proportions = true,
}
```

BTW I think this should be default option.

**Closed** 2023-01-03 15:15 UTC

**Comment by siduck** [comment] 2023-04-04 00:02
@VioletXF ik im late, done!
